behavior:

  behavior_list: [
    #  x,y,yaw
    [ 4.0, 0.0, 1.579 ],
    [ 2.5, 0.0, 0.0 ],
    [ 4.0, 0.0, 1.579 ],
    [ 2.5, 0.0, 0.0 ],
    [ 4.0, 0.0, 1.579 ],
    [ 2.5, 0.0, 0.0 ],
    [ 4.0, 0.0, 1.579 ],
    [ 2.5, 0.0, 0.0 ],
  ]